[GLOBAL]
pants_version = "2.24.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.experimental.go",
  "pants.backend.experimental.javascript",
  "pants.backend.experimental.typescript",
]

[python]
interpreter_constraints = ["CPython>=3.8,<4"]
source_roots = [
  "python",
  "go/cli/internal/cli",
]

[go]
expected_version = "1.21"
source_roots = ["go"]

[javascript]
source_roots = ["ui"]
