[GLOBAL]
pants_version = "2.24.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.experimental.go",
  "pants.backend.experimental.javascript",
  "pants.backend.experimental.typescript",
]

# [python]
# source_roots = ["python"]

# [golang]
# minimum_expected_version = "1.19"
# source_roots = ["go"]

# [javascript]
# source_roots = ["ui"]
